[package]
name = "humus"
version = "0.0.1"
edition = "2021"

[dependencies]
chrono = "0"
headers = "0"
http-body-util = "0"
hyper = { version = "1", features = ["full"] }
hyper-util = { version = "0", features = ["full"] }
tokio = { version = "1", features = ["full"] }
async-trait = "0"