name: cargo test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Build
      run: cargo build
      
    - name: Run tests
      run: cargo test
      
    - name: Publish
      if: github.event_name != 'pull_request'
      run: cargo publish --token "$CRATES_TOKEN"
      env:
        CRATES_TOKEN: ${{ secrets.CRATES_TOKEN }}
